name: Semantic Release

on:
  push:
    branches: [main]
  pull_request:
      branches: [main]

jobs:
  build:
    name: Deploy to staging
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: |
          ls --all
          yarn build

      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

permissions:
  contents: write
